### ISSUE TITLE
Require go 1.14+ to compile coral binary

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/testnets#11]
There was a nasty and subtle bug with go 1.13 that @KamiD was kind enough to debug in #9 

Let's avoid any more issues and please make a bold entry that Go 1.14+ is required to compile, something to do with the build flags setting the address prefix.

**Comment by orkunkl** [comment]
I added v1.14 to testnet doc. Should we bump it in https://github.com/CosmWasm/wasmd/blob/master/go.mod#L3 as well? @ethanfrey

**Comment by ethanfrey** [comment]
Yes, please do. As well as the wasmd README - https://github.com/CosmWasm/wasmd/issues/245
