### ISSUE TITLE
Spin a machine

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/testnets#118]
Launch a machine on hetzner that will host juno node and explorer.

---

Project: Misc
Name: juno-fleet
Location: Falkenstein
Type: CX21
Extra volume: 40 GB
Firewall: Accepts 22, 443, 80, For outgoing you do your magic :)

Volume must be attached to the system and fstab. Hetzner UI shows how to do.
You can attach it to `/mnt/data`. Decide the naming
Juno application home will be stored in this volume so we can attach to another machine if needed

**Comment by orkunkl** [comment]
@migmeneses

**Comment by migmeneses** [comment]
Hi there,
"Firewall: Accepts 22, 443, 80, For outgoing you do your magic :)"
Would you like me to achieve this with 'ufw' or the one provided by Hetzner ( I think the last could be the best )

**Comment by migmeneses** [comment]
I just created this firewall:
https://console.hetzner.cloud/projects/553357/firewalls/54673/rules

I will proceed with the spin-up of the new machine

**Comment by migmeneses** [comment]
VM: juno-fleet has been deployed
for the extra volume, Hetzner decided the name
Also, the volume is present on /etc/fstab, so we could de-attach it

```
root@juno-fleet:~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0 38.2G  0 disk 
├─sda1    8:1    0 38.1G  0 part /
├─sda14   8:14   0    1M  0 part 
└─sda15   8:15   0   61M  0 part /boot/efi
sdb       8:16   0   40G  0 disk /mnt/HC_Volume_11575432
sr0      11:0    1 1024M  0 rom
```  

```
root@juno-fleet:~# mount | grep "/dev/sdb"
/dev/sdb on /mnt/HC_Volume_11575432 type ext4 (rw,relatime,discard)
```
Link for the resource:
https://console.hetzner.cloud/projects/553357/servers/12212161/overview

**Comment by migmeneses** [comment]
Alright, the VM still semi-virgin ( I have checked and install sudo, git and vim )
Also, added users alex, ethan, miguel and orkunkl
they can ssh directly using their ssh keys to their respective usernames, not need for passwords as long they are using the right key
Example:
[ from Miguel's host ]

```
miguel@loving-wescoff:~$ ssh <IP>
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

miguel@juno-fleet:~$ 

```

**Comment by orkunkl** [comment]
## Firewall
Inbound: 22, 443, 80/tcp
Outbound: 443, 80/tcp, 53/udp, These are for domain resolution and apt updates.

**Comment by orkunkl** [comment]
After you solve the firewall issue above, you can close the issue.

**Comment by migmeneses** [comment]
> "Inbound: 22, 443, 80/tcp
> Outbound: 443, 80/tcp, 53/udp, These are for domain resolution and apt updates."

Done!

**Comment by migmeneses** [comment]
Be aware the server still virgin ( or semi virgin )

**Comment by migmeneses** [comment]
We declared this case Done!

**Comment by orkunkl** [comment]
Great job!
