### ISSUE TITLE
Download and install juno

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/testnets#119]
The process is very similar to what we did on the first day.

Swap wasmd with junod

1- Install Go 1.15+
2- `git clone https://github.com/CosmosContracts/Juno`
3- `make install` and place to path.

**Comment by orkunkl** [comment]
Info: install juno to the server and your local too

**Comment by migmeneses** [comment]
Regarding Juno compiling and build:
```
miguel@juno:~/Juno$ make install
go: github.com/cosmos/cosmos-sdk@v0.42.5: missing go.sum entry; to add it:
        go mod download github.com/cosmos/cosmos-sdk
go: github.com/cosmos/cosmos-sdk@v0.42.5: missing go.sum entry; to add it:
        go mod download github.com/cosmos/cosmos-sdk
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=juno -X github.com/cosmos/cosmos-sdk/version.AppName=junod -X github.com/cosmos/cosmos-sdk/version.Version=main-2b03ba3234b4870dafe9992eb1d00f74360b3e1e -X github.com/cosmos/cosmos-sdk/version.Commit=2b03ba3234b4870dafe9992eb1d00f74360b3e1e -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/tendermint/tendermint/version.TMCoreSemVer= -w -s' -trimpath ./cmd/junod
go: github.com/cosmos/cosmos-sdk@v0.42.5: missing go.sum entry; to add it:
        go mod download github.com/cosmos/cosmos-sdk
make: *** [Makefile:92: install] Error 1
```
You can find the details from 'juno' on project onboard-node-operator
PS. 'juno' has been setup just for testing purposes before moving to 'juno-fleet'

**Comment by migmeneses** [comment]
I've installed comos-sdk and tendermint, and still getting the above error, I will try the setupon DigitalOcean
Be aware when I did try the above but with the go installatilltion from download, the error was different

...continue...

**Comment by orkunkl** [comment]
This is not because of mising cosmos-sdk or tendermint, Normally golang should download all. I will check the problem now.

**Comment by orkunkl** [comment]
So found the problem, install golang `1.16` and try again. Juno updated the golang version

**Comment by migmeneses** [comment]
@orkunkl Where did you test or check? 
I would like to see it. Golang 1.16.4 is installed and I still get the same error.
Also, I tried on Digital Ocean, the same issue, I think we are missing a dependency

**Comment by migmeneses** [comment]
@orkunkl This is not working
I still get the same error, whatever is golang 1.15 or 1.16

VM: `juno` on project `onboard-no-op`

**Comment by migmeneses** [comment]
After a private talk with Orkun
1. Install Golang - [link](https://github.com/golang/go/wiki/Ubuntu)
2. Clone the repository: `git clone https://github.com/CosmosContracts/Juno.git`
3. Place yourself on the Juno directory: `cd Juno`
4. Run `go mod tidy`
> This command will download all the dependencies that are required in your source files and update go.mod file with that dependency.

5. Run: `make install` , `make build` and move binary to a executable PATH, example: `/usr/local/bin`

Installed locally and on `juno-2` from project `onboard-node-op`

**Comment by migmeneses** [comment]
VM: `juno-fleet`
Volume being mount: `/mnt/data`

Ran, Initialized validator:
`sudo junod init localnet --chain-id ${CHAIN_ID} --home ${APP_HOME}`
where, variables:
```
APP_HOME="/mnt/data/.junod/"
CHAIN_ID="localnet"
```
`.junod/` is present on the Volume, such volume has rw permission for root and sudo users

Thinking to change those permissions to nobody:nogroup

**Comment by migmeneses** [comment]
@orkunkl let me what you think about it.
Regarding the volume being mount on `/mnt/data`
_Should I change the permission to write for everybody?_
If there is a similar node/VM on production, I could have a look, please

**Comment by orkunkl** [comment]
Looks all good!
