### ISSUE TITLE
Configure app.yaml

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/testnets#121]
```minimum-gas-prices = "???" 
pruning=custom
pruning-keep-recent=362880 
pruning-keep-every=0 
pruning-interval=100
```
/// api 
```
api = enable
enabled-unsafe-cors = true
```

**Comment by migmeneses** [comment]
Probably, you mean:

pruning = "custom"
pruning-keep-recent = "362880"
pruning-keep-every = "0"
pruning-interval = "100"

[api]
enable = true
enabled-unsafe-cors = true

**Comment by migmeneses** [comment]
@orkunkl you can have a look on `juno-fleet `within `Misc` project and `juno-2` within `onboard-node-op`

**Comment by migmeneses** [comment]
be aware `juno-2` has its $AP_HOMEon the regular home directory

**Comment by orkunkl** [comment]
`juno-2` and `juno-fleet` approved
