### ISSUE TITLE
Start the node and let it sync

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/testnets#123]
Run the app with tmux or systemd.
If all correct node will start syncing with the rest of the network.
This will take time. You can compare the local height with the latest height at https://testnet.juno.aneka.io

**Comment by migmeneses** [comment]
@orkunkl 
https://docs.junochain.com/validators/joining-the-testnets#joining-after-genesis
Is this the right path?

**Comment by orkunkl** [comment]
@migmeneses 
You completed the steps in that doc.
Now just start the junod with systemd.

**Comment by orkunkl** [comment]
Here is systemd file: `junod.service`

```
[Unit]
Description=junod
Requires=network-online.target
After=network-online.target

[Service]
TimeoutStartSec=5
Restart=always
User=root
Group=root
Environment=APP_HOME=<APP_HOME>
Environment=BINARY=<JUNO_BINARY_LOCATION>
ExecStart=$BINARY start --rpc.laddr tcp://0.0.0.0:26657 --home $APP_HOME
KillSignal=SIGKILL

[Install]
WantedBy=multi-user.target
```
Put the correct env variables

**Comment by migmeneses** [comment]
Funny, I was setting up the juno.service file when you posted the above
Thank you!

**Comment by migmeneses** [comment]
OK, this is the current /etc/systemd/system/junod.service
```
[Unit]
Description=Juno daemon
Requires=network-online.target
After=network-online.target

[Service]
TimeoutStartSec=5
Restart=always
User=root
Group=root
ExecStart=/usr/local/bin/junod start --rpc.laddr tcp://0.0.0.0:26657 --home /mnt/data/.junod
KillSignal=SIGKILL

[Install]
WantedBy=multi-user.target

```
Now, we could manage junod via systemd,

Also, you can run execute directly
`sudo junod start --rpc.laddr tcp://0.0.0.0:26657 --home /mnt/data/.junod`
We could find a way to register all those outputs into a log ( maybe it is too much to ask )

On the firewall, Should we open the ports 26656, 26657, 9090, and 1317?

[Picture attached]

**Comment by migmeneses** [comment]
![Screenshot from 2021-06-09 14-16-37](https://user-images.githubusercontent.com/39744352/121352912-fe30e900-c935-11eb-8eb2-562fe70221ab.png)

**Comment by migmeneses** [comment]
just to comment, Firewall has been edited, we open inbound and outbound port: 26656

**Comment by migmeneses** [comment]
I know the case/ticket/issue is closed but,
I still getting:
```
Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected AE6FB28BBC668B471C31C51B585DA568C81640CDDD5954607EE658C8BF1BCE34, got CFDF06864AF57
BACF7E37BF7F85886E57BEFECE8D74ED463CA36EFAA59F1690C 
```
After a few hours of running the application and/or process

You can find it on $USER=miguel , tmux sessions `junod`

**Comment by migmeneses** [comment]
UPDATE: I am giving it a new try

**Comment by migmeneses** [comment]
The results are not good:
I still getting the same output around height=137345
```
1:30PM INF commit synced commit=436F6D6D697449447B5B31373420313131203137382031333920313838203130322031333920373120323820343920313937203237203838203933203136352031303420323030203232203634203230352032323120383920383420393620313236203233302038382032303020313931203237203230362035325D3A32313838317D
1:30PM INF committed state app_hash=AE6FB28BBC668B471C31C51B585DA568C81640CDDD5954607EE658C8BF1BCE34 height=137345 module=state num_txs=1
panic: Failed to process committed block (137346:A2E477D4C3ACFA9BA18C41347FE4EC08E7AD03653627B8402BC211D1D9DEA315): wrong Block.Header.AppHash.  Expected AE6FB28BBC668B471C31C51B585DA568C81640CDDD5954607EE658C8BF1BCE34, got CFDF06864AF57BACF7E37BF7F85886E57BEFECE8D74ED463CA36EFAA59F1690C

goroutine 180 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0000f5180, 0x0)
        github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:401 +0x15bf
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.10/blockchain/v0/reactor.go:110 +0x8c
```

**Comment by migmeneses** [comment]
UPDATE: I just downloaded a snapshot provided by wabam ( a validator from discord )
Currently syncing for a 4th time but with different data on` /mn/data/.junod/data`

**Comment by migmeneses** [comment]
It works!
It is SYNC now!
