### ISSUE TITLE
Setup Block Explorer

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/testnets#125]
# Introduction

Block explorer is a blockchain monitoring tool. 
It shows all the validators, txs, blocks, proposals and more 
Here is a live one that listens cosmos hub mainnet 
https://cosmos.bigdipper.live/
We use a fork of this project. 
See here : https://block-explorer.oysternet.cosmwasm.com/

## Setup

Setup scripts are here
https://github.com/CosmWasm/testnets/tree/master/devops/block-explorer

README.md contains the setup phases.
**But** there is no `block-explorer-settings.json` generated for juno. You have to prepare it.
Try it yourself, if you have any questions let me know.

**Comment by migmeneses** [comment]
right,
Should I boot a new VM for this?

**Comment by migmeneses** [comment]
Started/spin up initial setup accordingly

**Comment by migmeneses** [comment]
how can I configure or create block-explorer-settings.json?

**Comment by migmeneses** [comment]
per previous conversation, the example has been provided
Now, has juno its own block-explorer?

**Comment by migmeneses** [comment]
Hi @orkunkl 
Should we build the block-explore for Juno?
https://console.hetzner.cloud/projects/553357/servers/12443588/overview

I have done nothing yet, I wanted to ask:
What should change from `block-explorer-settings.json`?
I do have an idea, but wanted to check with you first

**Comment by orkunkl** [comment]
Best approach:
- Checkout to juno-testnet-1(or whatever the chain-id is) and create testnet directory
- Write `block-explorer-settings.json` and send a PR request

**Comment by migmeneses** [comment]
I've setup a few block-explorers now
So, I will declare this cases as closed
