### ISSUE TITLE
cliffnet-1 faucet endpoint is down

### ISSUE THREAD

**Issue by cameronfyfe** [CosmWasm/testnets#146]
https://faucet.cliffnet.cosmwasm.com/ stopped working on (or maybe before) April 14 for me and I'm wondering if anyone knows anything about it's status.  It was working previously but now I only see 502 responses for all requests.  Is this still the preferred method of acquiring tokens on cliffnet-1?

Thanks in advance for any help!

**Comment by suhjohn** [comment]
same issue

**Comment by migmeneses** [comment]
This is an old request and it has been fixed
