### ISSUE TITLE
Getting insufficient free tokens from cliffnet

### ISSUE THREAD

**Issue by rashid3011** [CosmWasm/testnets#153]
I am following the steps provided in this documentation - [](https://docs.cosmwasm.com/docs/1.0/getting-started/intro)

`wasmd keys add fred` - here i am just creating a wallet named fred.

`JSON=$(jq -n --arg addr $(wasmd keys show -a fred) '{"denom":"upebble","address":$addr}') && curl -X POST --header "Content-Type: application/json" --data "$JSON" https://faucet.cliffnet.cosmwasm.com/credit` - Trying to get free tokens to interact.

`RES=$(wasmd tx wasm store target/wasm32-unknown-unknown/release/voting.wasm --from fred $TXFLAG -y)` - Trying to store the bytecode in chain.

but if do the `echo $RES`, i am getting this error

`code: 13 codespace: sdk raw_log: 'insufficient fees; got: 1588usponge required: 15877upebble: insufficient fee' txhash: 96290B0DCB6452645EA655D8189CA2F7045B4958A024A104B98023BE96536263`

what might be the issue?

**Comment by webmaster128** [comment]
You provide 1588usponge but the transaction requires 15877upebble. Those are different tokens.

**Comment by webmaster128** [comment]
~Wait a second, this is a configuration error of the faucet~

**Comment by webmaster128** [comment]
What's the value of `$TXFLAG`?

**Comment by webmaster128** [comment]
Cliffnet will be shut down shortly. Please migrate to https://github.com/CosmWasm/testnets/tree/master/malaga-420. The CosmWasm docs should be using malaga-420 already. Also see the CosmWasm book: https://book.cosmwasm.com/wasmd-quick-start/testnet.html
