### ISSUE TITLE
Set up demo-10 chain

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/testnets#2]
Blocked on `wasmd v0.10.0` release

Before we go to coral, we should have a local "dev net" using 0.10 that we can test all our code full-stack against, try the faucet, the code explorer, etc. And shake out any bugs before going public.

We can do a centralized start as with demo-09,08,...

I would add a second node with 50% of the validator power later on just to ensure we halt if there is any non-determinism.

- [x] Set up this network (node, rpc, lcd, and faucet)
- [x] Add to testnet docs (replacing demo-09)
- [x] Update docs2 to use demo-10 (maybe some code needs to be updated, definitely the links)
- [x] Deploy wasm.glass to it
- [x] Point name-app to it
- [x] Add second validator (to check for non-determinism)

**Comment by orkunkl** [comment]
I am going to read terraform tutorials quickly while waiting for our workhorse machines. Afterward, you can send any auth keys etc to https://keybase.io/orkunkl if there are

**Comment by ethanfrey** [comment]
You can cut out the terraform part also... it was just to create a machine and set up the dns entries. Probably 5 minutes of manual work. Easier to do by hand than mess with terraform.

The setup scripts (look at the files provider part in terraform - it calls these scripts) is what is important. And it is just straight bash

**Comment by orkunkl** [comment]
The last 3 points will be done on Monday.

**Comment by ethanfrey** [comment]
name-app is working

**Comment by ethanfrey** [comment]
I think @webmaster128 will take care of wasm.glass

@orkunkl can you set up a second node as a non-validator. I will send you some stake when you set it up so you can bond the node into a validator

**Comment by orkunkl** [comment]
On the same machine?

**Comment by ethanfrey** [comment]
Nope, on a second one.
It doesn't need nginx or faucet or anything but a node that connects over p2p

**Comment by ethanfrey** [comment]
I will set you up with a machine

**Comment by webmaster128** [comment]
https://demonet.wasm.glass/ is re-deployed with a cosmwasm 0.10 setup

**Comment by orkunkl** [comment]
Second validator is running. Both on `v0.10.0`

**Comment by orkunkl** [comment]
Looks like all the points up there is done. If there is nothing else, let's move this to done 💪

**Comment by ethanfrey** [comment]
Done. Very nice! Can you update the docs with how you connected the node? (this is the path we want people to follow for coralnet and gaiaflex)

Once you add that, please close this issue

**Comment by orkunkl** [comment]
I followed up https://docs.cosmwasm.com/testnets/testnets.html#joining-running-testnets for connecting the node. I suppose that's docs look enough. @ethanfrey if you think the same we can close the issue.

**Comment by ethanfrey** [comment]
Yup. Done
