### ISSUE TITLE
change default slashing params in genesis.json. make slashing more suitable

### ISSUE THREAD

**Issue by KamiD** [CosmWasm/testnets#22]
# Problem
Our default slashing params which is writing in  `genesis.json` is very stringent, it will make some validators jailed very fast ( cause missing block sign ), we need change it more larger to make sure the good validator will working without unexpected things~
# Todo
Change Slashing params to :
```json
"slashing": {
      "missed_blocks": {},
      "params": {
        "downtime_jail_duration": "600000000000",
        "min_signed_per_window": "0.050000000000000000",
        "signed_blocks_window": "10000",
        "slash_fraction_double_sign": "0.050000000000000000",
        "slash_fraction_downtime": "0.010000000000000000"
},
``` 
such as the params of cosmos-hub: https://cosmos.ping.pub/#/parameter

**Comment by ethanfrey** [comment]
Good find. I agree
