### ISSUE TITLE
Add docs on how to use smart contracts

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/testnets#51]
On the docs site:

- [x] cw20 (init and execute)
- [x] subkeys (init and execute)

**Comment by ethanfrey** [comment]
Related to https://github.com/CosmWasm/docs2/issues/13

This one can just be the contract-specific commands, then let's include the context and general walk-through of `@cosmjs/cli` on coralnet with the other issue.

**Comment by orkunkl** [comment]
Points are resolved. Closing the issue. I am thinking maybe CosmJS deserves it's own section on the docs. Or maybe separate docs repo at some point 🤔
