### ISSUE TITLE
Document how to use governance votes in gaia flex

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/testnets#54]
Rough info is here: https://github.com/CosmWasm/wasmd/blob/master/x/wasm/Governance.md

Ask @alpe if you need more details.

- [x] Start up simple devnet with gaiaflex binary (and fast, eg. 10 minute governance cycle)
- [x] Try uploading contracts (via governance)
- [x] Try instantiateing contracts (via governance)
- [ ] Try executing contracts normally
- [ ] Document all steps.

(you can use the cw20 contract for examples)

**Comment by orkunkl** [comment]
gaia-flex-tmp is ready at http://95.217.166.214:26657 for documenting and testing.
