### ISSUE TITLE
Deploy LCD

### ISSUE THREAD

**Issue by orkunkl** [CosmWasm/testnets#55]
Endpoint: https://lcd.gaia-flex.cosmwasm.com:443

**Comment by orkunkl** [comment]
<del>I launched CX11(1 CPU, 2gb ram, 20 GB storage) for LCD. I assume this will be enough for it. Let's save some money</del>

**Comment by orkunkl** [comment]
Sorry I saw you already reserved a machine for LCD and assigned the task to yourself :+1:

**Comment by ethanfrey** [comment]
Done.
