### ISSUE TITLE
Publicize coralnet more widely

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/testnets#56]
So people use the contracts

**Comment by orkunkl** [comment]
Started to infiltrate rust communities :smiling_imp:. https://users.rust-lang.org/t/webassemly-rust-on-blockchain-cosmwasm/47450. I will post there if some traction happens.

**Comment by orkunkl** [comment]
https://www.reddit.com/r/rust/new/ is a good place to advertise
