### ISSUE TITLE
Set up genesis file for gaia-flex

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/testnets#8]
* add-account for every account that voted on proposal 25
* Every account should have 10k muon
* 3 members of cosmwasm should have special accounts with 50k muon to provide some stability when bootstrapping (those devs should make separate prs)

Adding: `gaiaflex add-genesis-account --home . $ADDR 10000000000umuon`

Getting the list: 
* `gaiacli query gov votes 25` only shows one page (30), as does hubble
* https://cosmos.bigdipper.live/proposals/25 has far more votes
* please try to get the full list that bigdipper gives (they use websockets, so not so easy to grab their api calls... maybe asking on a forum?)

**Comment by orkunkl** [comment]
I modified a cosmos-based app that uses cosmos master and setup correct config value then
```sh
xcli gov votes 25 --limit=10000000
```
and Voila!  
There are 183 voters in total. Should I include `No` and `NoWithVeto` votes?
[voters.txt](https://github.com/CosmWasm/testnets/files/5028384/voters.txt)

**Comment by ethanfrey** [comment]
Yes, please include everyone who voted.

The point was not to buy yes votes, but to get a list of anyone who cared enough to vote. The no voters should have a chance to try to break it and show how it is insecure.
